#spring.application.name=ApnaBazarBackend
#mysql database information
spring.datasource.url=jdbc:mysql://localhost:3307/apna_db
spring.datasource.username=root
spring.datasource.password=root

#JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate Dialect\
spring.jpa.hibernate.ddl-auto=update

spring.config.name=

spring.jpa.show-sql=true

